services:
  - type: web
    name: anti-ta7ayol-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend/src.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
