# routers/classify_router.py
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/classify", tags=["Classification"])

class ClassifyRequest(BaseModel):
    text: str
    url: Optional[str] = None  # Optional input

@router.post("/")
def classify_pipeline(request: ClassifyRequest):
    text = request.text
    url = request.url

    # 👇 Dummy logic for now — this will later be replaced with actual model calls
    score2 = 0.83  # Similarity check result
    score3 = 0.91  # Fact check result
    score1 = 0.74 if url else None  # URL enrichment if url provided

    # Dummy final score computation
    if score1 is not None:
        final_score = (2 * score3 * score2 * score1) / (score3 * score2 + score2 * score1 + score1 * score3 + 1e-8)
    else:
        final_score = (2 * score3 * score2) / (score3 + score2 + 1e-8)

    # Dummy rapport (for now, will be generated by LLM later)
    rapport = f"This message is likely {'a scam' if final_score > 0.7 else 'safe'} based on our current analysis."

    return {
        "rapport": rapport
    }
